FROM mcr.microsoft.com/devcontainers/cpp:1-ubuntu-24.04

RUN sudo apt-get -y update && sudo apt-get install  -y libgl1-mesa-dri \
    libglx-mesa0 \
    mesa-utils \
    libgl1-mesa-dri \
    libglm-dev\
    libx11-dev \
    libxrandr-dev \
    libxinerama-dev \
    libxcursor-dev \
    libxi-dev \
    libxext-dev \
    libxfixes-dev
    libwayland-dev 
    



